eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000}/eureka/
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
logging:
  file:
    name: C:\logs\springboot.log
  level:
    root: INFO
    tn:
      esprit:
        repository: INFO
        service: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{36} - %msg%n'
server:
  port: 8081
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: ${MONGO_URI}
  profiles: heroku
